package kg.geektech.game.players;

public enum SuperAbility {
    CRITICAL_DAMAGE, BOOST, HEAL, SAVE_DAMAGE_AND_REVERT,INVISIBLE,FROZEN,BLOCK,KAMIKADZE_OFFERING,PLAY_DEAD,SHOT_SHURIKEN,HACKER_SKILL,DEKU_SKILL
}
